//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMVCMySql
{
    using System;
    using System.Collections.Generic;
    
    public partial class code_violation
    {
        public int code_violation_id { get; set; }
        public string code_violation_nk { get; set; }
        public string code_violation_suffix { get; set; }
        public string code_violation_name { get; set; }
    }
}
